version: '3.8'

services:
  bot:
    build: .
    container_name: kraken-bot
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - ./bot_state.json:/app/bot_state.json
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; assert os.path.exists('bot_state.json')"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 